# 数组基础

In [35]:
import numpy as np

In [36]:
# 设置随机数种子
np.random.seed(0);
# 一维数组
array1=np.array([0, 1, 2, 3, 4, 5]);
# 二维数组
array2=np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15]]);

## 数组的属性

In [37]:
# 数组的维度
print("array1维度：", array1.ndim);
print("array2维度：", array2.ndim);
# 数组的每个维度的大小
print("array1每个维度大小：", array1.shape);
print("array2每个维度大小：", array2.shape);
# 数组的总大小
print("array1数组的总大小：", array1.size);
print("array2数组的总大小：", array2.size);

array1维度： 1
array2维度： 2
array1每个维度大小： (6,)
array2每个维度大小： (2, 6)
array1数组的总大小： 6
array2数组的总大小： 12


## 数组索引：获取单个元素

In [38]:
print(array1);
# 正数索引表示从左往右数，从0开始
print(array1[1]);
# 负数索引表示从右往左数
print(array1[-1]);

[0 1 2 3 4 5]
1
5


## 数组切片：获取子数组

In [39]:
print(array1);
# 数组切片遵循 array[开始索引:结束索引:步长]的模式
# 索引0到4之间的元素，并且每2个元素取一个
print("array1[0:4:2]: ", array1[0:4:2]);
# 前3个元素
print("array1[:3]: ", array1[:3]);
# 索引3之后的元素
print("array1[3:]: ", array1[3:]);
# 间隔一个元素
print("array1[::2]: ", array1[::2]);

[0 1 2 3 4 5]
array1[0:4:2]:  [0 2]
array1[:3]:  [0 1 2]
array1[3:]:  [3 4 5]
array1[::2]:  [0 2 4]


In [40]:
print(array2);
# 两行，三列
print("array2[:2, :3]");
print(array2[:2, :3]);

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]
array2[:2, :3]
[[ 0  1  2]
 [10 11 12]]


## 数组的拼接与分割

In [46]:
# 3个数组拼接成1个数组
array3=np.array([1, 2, 3]);
array4=np.array([4, 5, 6]);
array5=np.array([7, 8, 9]);
array6=np.concatenate([array3, array4, array5]);
print(array6);

[1 2 3 4 5 6 7 8 9]


In [47]:
# 1个数组分割成3个数组
array7, array8, array9 = np.split(array6, [3, 6]);
print(array7, array8, array9);

[1 2 3] [4 5 6] [7 8 9]
